export { designImages } from './mock/assets'
export { categories } from './mock/category'
export { coupons } from './mock/coupon'
export { cityRegions, hotSearchWords } from './mock/location'
export { orders } from './mock/order'
export { sportRecords } from './mock/record'
export { reviews } from './mock/review'
export { slots, venueDates } from './mock/schedule'
export { favoriteVenues, findVenue, venues } from './mock/venue'
